version: "3.8"

services:
    postgres_database:
        image: postgres:15.2-alpine
        container_name: postgres_database
        restart: always
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
        ports:
            - "5432:5432"
        volumes:
            - ./db-init/init.sql:/docker-entrypoint-initdb.d/init.sql
            # - ./data:/var/lib/postgresql/data

    mongo_database:
        image: mongo:5.0.3
        container_name: mongo_database
        restart: always
        ports:
            - "27017:27017"
        volumes:
            - ./db-init/mongo-init.js:/docker-entrypoint-initdb.d/init-mongo-db-with-collections.js
            # - ./data:/data/db

